In [1]:
import numpy as np

k = 11

values = np.array([[180, 140, k, 245 - 4*k, 232],
                   [420, 120 + 10*k, 140, 220, 100],
                   [25 + 8*k, 315, 35, 49, 10 * (k+23) - 50],
                   [290 - 10*k, k, 9, 100*k -90, 201]])

a = 1 / (k + 3) if(1 <= k <= 12) else 4/k 

p = np.array([0.1, 0.2, a, a + 0.1, 0.6 - 2*a])

print("λ: ", a)
print("\np: ", p)
print("\nValues:\n", values)


λ:  0.07142857142857142

p:  [0.1        0.2        0.07142857 0.17142857 0.45714286]

Values:
 [[ 180  140   11  201  232]
 [ 420  230  140  220  100]
 [ 113  315   35   49  290]
 [ 180   11    9 1010  201]]


## Песимізм

In [2]:
pesMinValues = np.min(values, 1)
pesMaxIndex = np.argmax(pesMinValues)

print(pesMinValues)
print("Найкраще вибрати варіант", pesMaxIndex+1)


[ 11 100  35   9]
Найкраще вибрати варіант 2


## Оптимізм

In [3]:
optMaxValues = np.max(values, 1)
optMaxIndex = np.argmin(optMaxValues)

print(optMaxValues)
print("Найкраще вибрати варіант", optMaxIndex+1)

[ 232  420  315 1010]
Найкраще вибрати варіант 1


## Гурвіц

In [4]:
hurvitsValues = np.min(values,1) * a + (1-a) * np.max(values,1)

print(hurvitsValues)
print("Найкраще вибрати варіант", np.argmax(hurvitsValues)+1)

[216.21428571 397.14285714 295.         938.5       ]
Найкраще вибрати варіант 4


## Лаплас

In [5]:
laplasValues = np.average(values, 1)

print(laplasValues)
print("Найкраще вибрати варіант", np.argmax(laplasValues)+1)

[152.8 222.  160.4 282.2]
Найкраще вибрати варіант 4


## Баєс-Лаплас

In [6]:
bayesValuesIntermediate = values*p
bayesValues = np.sum(bayesValuesIntermediate, 1)

print(bayesValues)
print("Найкраще вибрати варіант", np.argmax(bayesValues)+1)

[187.3        181.42857143 217.77142857 285.87142857]
Найкраще вибрати варіант 4


## Ходж-Леман

In [7]:
lemanValues = (1-a) * pesMinValues + bayesValues * a

print(lemanValues)
print("Найкраще вибрати варіант", np.argmax(lemanValues)+1)

[ 23.59285714 105.81632653  48.05510204  28.77653061]
Найкраще вибрати варіант 2
