In [19]:
from model import *

Беремо матрицю парних порівнянь суджень та шукаємо для кожного критерію середньє геометричне та вагу

In [20]:
criteriaMeans = np.zeros(criterias.shape[1])

for i, criteria in enumerate(criterias):
    criteriaMeans[i] = g_mean(criteria)

criteriaMeansSum = np.sum(criteriaMeans, 0)


criteriaNormalized = np.zeros(criterias.shape[1])

for i, criteriaMean in enumerate(criteriaMeans):
    criteriaNormalized[i] = criteriaMean / criteriaMeansSum

print("Means of criterias:", criteriaMeans)
print("\nSum:", criteriaMeansSum)
print("\nNormalized:", criteriaNormalized)

Means of criterias: [0.2933259  1.25598354 2.03836954 0.92587471 0.73486725 0.28177603
 4.75563452 1.12983096 1.29269365]

Sum: 12.708356095104403

Normalized: [0.02308134 0.09883131 0.160396   0.07285558 0.05782552 0.0221725
 0.37421319 0.08890457 0.10171997]


Для кожного критерію дивимося яка машина краща в ньому і повторюємо ті самі кроки, тобто середнє геометричне, щоб знайти вагу

In [21]:
means = np.zeros((criterias.shape[1], 3))

for i, criteria in enumerate(carsDifference):
    for j, car in enumerate(criteria):
        means[i][j] = g_mean(car)

meanSum = np.sum(means, 1)


normalizedValues = np.zeros((criterias.shape[1], 3))

for i, mean in enumerate(means):
    normalizedValues[i] = mean / meanSum[i]

print("Means:", means)
print("\nSum:", meanSum)
print("\nNormalized:\n", normalizedValues)

Means: [[0.30285343 0.92831777 3.5568933 ]
 [0.25131581 1.20507113 3.30192725]
 [0.82207069 3.97905721 0.30571071]
 [2.28942849 0.5        0.87358046]
 [3.5568933  0.30285343 0.92831777]
 [0.30571071 1.1856311  2.75892418]
 [0.28114422 3.30192725 1.07721735]
 [3.97905721 0.38157141 0.65863376]
 [0.30285343 3.30192725 1.        ]]

Sum:
 [4.7880645  4.75831419 5.10683861 3.66300895 4.7880645  4.25026599
 4.66028882 5.01926238 4.60478068]

Normalized:
 [[0.06325174 0.19388163 0.74286662]
 [0.05281615 0.2532559  0.69392796]
 [0.16097448 0.77916251 0.05986301]
 [0.62501307 0.1364998  0.23848712]
 [0.74286662 0.06325174 0.19388163]
 [0.07192743 0.27895457 0.649118  ]
 [0.06032764 0.70852417 0.23114819]
 [0.79275736 0.07602141 0.13122122]
 [0.06576935 0.71706504 0.21716561]]


Після чого рахуємо глобальний пріорітет відносно минулої інформації

In [22]:
globalPriorities = np.zeros(3)

for i in range(len(globalPriorities)):
    globalPriorities[i] = np.sum(normalizedValues[:, i] * criteriaNormalized)

print(globalPriorities)

[0.22233185 0.51910425 0.2585639 ]


Тепер вибираємо машину з найкращим пріорітетом

In [23]:
bestIndex = np.argmax(globalPriorities)
print(f"\nWe should choose car number: {bestIndex + 1}, with the priority of: {globalPriorities[bestIndex]}")


We should choose car number: 2, with the priority of: 0.5191042522749547
